"""
pareto_optimizer.py — Multi‑Objective Pareto Optimization for MOL‑X

Implements a lightweight NSGA‑II style evolutionary optimizer that can balance
four objectives that are already produced by the generator pipeline:
  * molecular_weight (minimize)
  * logp (target range 2‑5, modelled as minimization of distance to 3.5)
  * qed (maximize)
  * binding_score (minimize – more negative is better)

The optimizer works directly on SMILES strings. It converts them to RDKit
``Mol`` objects, mutates them by random atom additions/removals, and evaluates
the objective vector using the existing ``rdkit_utils.compute_molecule_properties``
function.

It returns a Pareto‑front of non‑dominated solutions together with the full
population for visualisation.
"""

from __future__ import annotations

import random
from typing import List, Tuple, Dict

try:
    from rdkit import Chem
    from rdkit.Chem import AllChem
    RDKIT_OK = True
except ImportError:
    RDKIT_OK = False

# Import the existing property calculator – kept in utils/rdkit_utils.py
try:
    from .rdkit_utils import compute_molecule_properties
except Exception:
    compute_molecule_properties = None

# ─── Helper utilities ───────────────────────────────────────────────────────

def _mol_from_smiles(smi: str):
    mol = Chem.MolFromSmiles(smi)
    if mol is None:
        raise ValueError(f"Invalid SMILES: {smi}")
    return mol

def _random_mutation(mol):
    """Apply a simple mutation to a molecule.

    * With 50 % probability add a random atom (C, N, O, F) attached to a random
      heavy atom.
    * Otherwise remove a random leaf atom (degree = 1).  The mutation is kept
      simple to guarantee fast execution on a laptop during the hackathon.
    """
    rw = Chem.RWMol(mol)
    if random.random() < 0.5:
        # Add atom
        atom_sym = random.choice(["C", "N", "O", "F"])
        new_atom_idx = rw.AddAtom(Chem.Atom(atom_sym))
        # attach to a random existing atom
        target_idx = random.choice([a.GetIdx() for a in rw.GetAtoms()])
        rw.AddBond(new_atom_idx, target_idx, order=Chem.BondType.SINGLE)
    else:
        # Remove a leaf atom if possible
        leaf_idxs = [a.GetIdx() for a in rw.GetAtoms() if a.GetDegree() == 1]
        if leaf_idxs:
            rw.RemoveAtom(random.choice(leaf_idxs))
    return rw.GetMol()

# ─── Objective vector ───────────────────────────────────────────────────────

def _objective_vector(smi: str) -> Tuple[float, float, float, float]:
    """Return a tuple (mw, logp_dist, -qed, binding_affinity).

    * ``mw`` – to be minimized.
    * ``logp_dist`` – absolute distance from the ideal logP (3.5).
    * ``-qed`` – maximize QED => minimize its negative.
    * ``binding_affinity`` – already a negative number – lower is better.
    """
    if not compute_molecule_properties:
        raise RuntimeError("rdkit_utils.compute_molecule_properties not available")
    props = compute_molecule_properties(Chem.MolFromSmiles(smi))
    if props is None:
        raise ValueError("Failed to compute properties")
    mw = props["molecular_weight"]
    logp = props["logp"]
    qed = props["qed"]
    bind = props["binding_affinity"]
    logp_dist = abs(logp - 3.5)
    return (mw, logp_dist, -qed, bind)

# ─── Dominance check ───────────────────────────────────────────────────────

def _dominates(a: Tuple[float, ...], b: Tuple[float, ...]) -> bool:
    """Return True if ``a`` dominates ``b`` (Pareto sense)."""
    less_or_equal = all(x <= y for x, y in zip(a, b))
    strictly_less = any(x < y for x, y in zip(a, b))
    return less_or_equal and strictly_less

# ─── NSGA‑II style core algorithm ───────────────────────────────────────────

def pareto_optimize(
    seed_smiles: List[str],
    generations: int = 12,
    pop_size: int = 30,
) -> Dict[str, List[dict]]:
    """Run a simple multi‑objective NSGA‑II loop.

    Parameters
    ----------
    seed_smiles: List[str]
        Initial molecules (e.g., the top‑10 generated by the VAE).
    generations: int (default 12)
        Number of evolutionary cycles – modest to keep runtime < 5 s.
    pop_size: int (default 30)
        Size of the population; the seed set is padded with random mutations.

    Returns
    -------
    dict with keys:
        * ``population`` – list of dicts ``{"smiles": str, "objectives": List[float]}``
        * ``pareto_front`` – subset of non‑dominated individuals.
    """
    if not RDKIT_OK:
        raise RuntimeError("RDKit is required for Pareto optimization")

    # Initialise population – ensure we have `pop_size` members
    population = []
    for smi in seed_smiles:
        population.append(smi)
        if len(population) >= pop_size:
            break
    # Fill remaining slots with random mutations of seeds
    while len(population) < pop_size:
        parent = random.choice(seed_smiles)
        try:
            mol = _mol_from_smiles(parent)
            mutated = _random_mutation(mol)
            population.append(Chem.MolToSmiles(mutated, isomericSmiles=True))
        except Exception:
            # fallback – just duplicate a seed
            population.append(random.choice(seed_smiles))

    # Evolutionary loop
    for gen in range(generations):
        # Evaluate objectives for current population
        objs = []
        for smi in population:
            try:
                objs.append((_objective_vector(smi), smi))
            except Exception:
                # Infeasible molecules get worst possible score
                objs.append(((float('inf'), float('inf'), float('inf'), float('inf')), smi))

        # Fast non‑dominated sort – produce Pareto front indices
        front = []
        for i, (obj_i, smi_i) in enumerate(objs):
            dominated = False
            for j, (obj_j, _) in enumerate(objs):
                if i != j and _dominates(obj_j, obj_i):
                    dominated = True
                    break
            if not dominated:
                front.append(i)

        # Selection: keep the front + fill up to pop_size with random survivors
        new_population = [objs[i][1] for i in front]
        while len(new_population) < pop_size:
            # Tournament selection (2 individuals)
            a, b = random.sample(objs, 2)
            winner = a if _dominates(a[0], b[0]) else b
            new_population.append(winner[1])

        # Variation: apply mutation to a subset (≈30 %)
        mutated_pop = []
        for smi in new_population:
            if random.random() < 0.3:
                try:
                    mol = _mol_from_smiles(smi)
                    mutated = _random_mutation(mol)
                    mutated_pop.append(Chem.MolToSmiles(mutated, isomericSmiles=True))
                except Exception:
                    mutated_pop.append(smi)
            else:
                mutated_pop.append(smi)
        population = mutated_pop

    # Final evaluation – generate full result payload
    final_objs = []
    for smi in population:
        try:
            obj = _objective_vector(smi)
        except Exception:
            obj = (float('inf'),) * 4
        final_objs.append({"smiles": smi, "objectives": list(obj)})

    # Extract Pareto front from final population
    pareto = []
    for i, entry_i in enumerate(final_objs):
        dominated = False
        for j, entry_j in enumerate(final_objs):
            if i != j and _dominates(tuple(entry_j["objectives"]), tuple(entry_i["objectives"])):
                dominated = True
                break
        if not dominated:
            pareto.append(entry_i)

    return {"population": final_objs, "pareto_front": pareto}

# ---------------------------------------------------------------------------
# Convenience wrapper used by the FastAPI endpoint (returns JSON‑serialisable data)
def optimize_payload(seed_smiles: List[str], generations: int = 12, pop_size: int = 30) -> dict:
    result = pareto_optimize(seed_smiles, generations=generations, pop_size=pop_size)
    front = result["pareto_front"]

    # Build top_candidates with resolved properties for the frontend
    top_candidates = []
    for entry in front:
        smi = entry["smiles"]
        try:
            props = compute_molecule_properties(Chem.MolFromSmiles(smi))
            top_candidates.append({
                "smiles": smi,
                "molecular_weight": props["molecular_weight"],
                "logp": props["logp"],
                "qed": props["qed"],
                "binding_score": props["binding_affinity"],
                "objectives": entry["objectives"],
            })
        except Exception:
            top_candidates.append({"smiles": smi, "objectives": entry["objectives"]})

    # Compute metrics ranges from the front
    mws = [c["molecular_weight"] for c in top_candidates if "molecular_weight" in c]
    qeds = [c["qed"] for c in top_candidates if "qed" in c]
    logps = [c["logp"] for c in top_candidates if "logp" in c]
    binds = [c["binding_score"] for c in top_candidates if "binding_score" in c]

    metrics = {}
    if mws: metrics["mw"] = [min(mws), max(mws)]
    if qeds: metrics["qed"] = [min(qeds), max(qeds)]
    if logps: metrics["logp"] = [min(logps), max(logps)]
    if binds: metrics["binding"] = [min(binds), max(binds)]

    return {
        "front_size": len(front),
        "generations_run": generations,
        "population_size": len(result["population"]),
        "top_candidates": top_candidates,
        "metrics": metrics,
        "pareto_front": front,
    }

"""End of pareto_optimizer.py"""
